### ISSUE TITLE
Add in pipeline step a conftest to check the requirements for DELETE events

### ISSUE THREAD

**Issue by lzecca78** [sighupio/fury-kubernetes-opa#37]
Hello!
since we have introduced the `protect namespace` rule that now forces each DELETE event through the gatekeeper, now became mandatory to exclude them from the other check in order to avoid misbehavior.
To do that, each violation block must have the following 3 lines :

```rego
operation := input.review.operation
any([ operation == "CREATE", operation == "UPDATE" ])
operation != "DELETE"
```

For this reason, should be a very smart usage of conftest, to add a pipeline step that enforces the presence of those lines.
Probably some rules need to be refactored in order to make the conftest rules easier,anyway, let's see them together!

**Comment by ralgozino** [comment]
We finally decided to make the rule for blocking accidental deletions optional, i.e. DELETE events are not passed by default.
