### ISSUE TITLE
Conflict with PodSecurityPolicy

### ISSUE THREAD

**Issue by simonemex** [sighupio/fury-kubernetes-opa#4]
If in the cluster is present `PodSecurityPolicy` it is necessary to remove the following annotation from Deployment manifest.
https://github.com/sighupio/fury-kubernetes-opa/blob/19a542a5b136e6a286b6c5f86898d7185870b121/katalog/gatekeeper/core/deploy.yml#L15-L18

Trying to install this module with `PodSecurityPolicy` running leaad to this error message in status section of `ReplicaSet`:
```
Warning  FailedCreate  11s (x19 over 22m)  replicaset-controller  Error creating: pods "gatekeeper-controller-manager-686c494bcd-" is forbidden: unable to validate against any pod security policy: [pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/manager]: Forbidden: seccomp may not be set]
```

**Comment by angelbarrera92** [comment]
Solved #6
