### ISSUE TITLE
Unique ingress breaks cert-manager

### ISSUE THREAD

**Issue by phisco** [sighupio/fury-kubernetes-opa#5]
The unique ingress rule breaks cert-manager, it tries to create a new ingress with a different path that would not be a problem, but is rejected nonetheless because it is an "ingress with the same host". 

Here the template: https://github.com/sighupio/fury-kubernetes-opa/blob/master/katalog/gatekeeper/rules/templates/unique_ingress_template.yml

The rule should be able to check hosts+path collisions, at least as much as possible, otherwise we should drop it.

**Comment by angelbarrera92** [comment]
In another project what i did was to exclude (whitelist) requests from a specific serviceAccount (in this case, cert-manager)

**Comment by phisco** [comment]
That could be an easier option, for sure adding a parameter for whitelisted users would be useful

**Comment by lnovara** [comment]
Adding a parameter for whitelisted users might be useful, but IMHO the main point about this rule is to avoid conflicting ingress definitions and same host with different paths is a perfectly fine use case that would fail validation as of now.

I agree with @phisco that the rule should check both host and path to fulfill its goal.

**Comment by phisco** [comment]
here you can find the working rule: https://play.openpolicyagent.org/p/yBBKpBccsQ

you can test it by changing the paths for the same host (sighup.io) in the data to have a different path `/test` => `/newTest`

**Comment by lnovara** [comment]
Awesome! I think we have a winner.

Can you open a PR?

**Comment by MarioUhrik** [comment]
Thanks for fixing this issue :+1: 
It was actually a pain point for me too - I've had two deployments deployed separately, each with their own ingress resource that shared the hostname but used a different path
